In [56]:
import statsmodels.api as sm
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.impute import SimpleImputer





In [57]:
df = pd.read_csv("Air_Quality_Monitoring_Data.csv")
df.columns = df.columns.str.lower()

df.head()

name                       gps          datetime    no2  o3_1hr  o3_4hr  \
0   Civic  (-35.285307, 149.131579)  04/10/2023 18:00    NaN   0.024   0.024   
1  Monash  (-35.418302, 149.094018)  04/10/2023 18:00  0.003   0.031   0.030   
2  Florey  (-35.220606, 149.043539)  04/10/2023 18:00  0.001   0.031   0.032   
3  Monash  (-35.418302, 149.094018)  04/10/2023 17:00  0.005   0.029   0.027   
4  Florey  (-35.220606, 149.043539)  04/10/2023 17:00  0.003   0.031   0.030   

   o3_8hr    co  pm10_1_hr  pm2_5_1_hr  ...  aqi_co  aqi_no2  aqi_o3_1hr  \
0   0.023  0.00       8.14        7.93  ...     0.0      0.0        24.0   
1   0.025  0.00       1.54        2.36  ...     0.0      3.0        31.0   
2   0.029  0.14       5.57        8.02  ...     1.0      1.0        31.0   
3   0.025  0.00       2.65        4.29  ...     0.0      4.0        29.0   
4   0.029  0.14       6.81        8.59  ...     1.0      2.0        31.0   

   aqi_o3_4hr  aqi_o3_8hr  aqi_pm10  aqi_pm2_5  aqi_site       date      time  
0        30.0        36.0      29.0       25.0      30.0  04-Oct-23  18:00:00  
1        37.0        39.0      30.0       25.0      37.0  04-Oct-23  18:00:00  
2        40.0        45.0      32.0       25.0      45.0  04-Oct-23  18:00:00  
3        34.0        38.0      32.0       25.0      34.0  04-Oct-23  17:00:00  
4        38.0        46.0      33.0       25.0      46.0  04-Oct-23  17:00:00  

[5 rows x 22 columns]

In [58]:
from datetime import datetime

df['datetime'] = pd.to_datetime(df['datetime'], format='%d/%m/%Y %H:%M')
df['datetime'] = df['datetime'].dt.month.astype(float)


In [59]:
df.head()

name                       gps  datetime    no2  o3_1hr  o3_4hr  o3_8hr  \
0   Civic  (-35.285307, 149.131579)      10.0    NaN   0.024   0.024   0.023   
1  Monash  (-35.418302, 149.094018)      10.0  0.003   0.031   0.030   0.025   
2  Florey  (-35.220606, 149.043539)      10.0  0.001   0.031   0.032   0.029   
3  Monash  (-35.418302, 149.094018)      10.0  0.005   0.029   0.027   0.025   
4  Florey  (-35.220606, 149.043539)      10.0  0.003   0.031   0.030   0.029   

     co  pm10_1_hr  pm2_5_1_hr  ...  aqi_co  aqi_no2  aqi_o3_1hr  aqi_o3_4hr  \
0  0.00       8.14        7.93  ...     0.0      0.0        24.0        30.0   
1  0.00       1.54        2.36  ...     0.0      3.0        31.0        37.0   
2  0.14       5.57        8.02  ...     1.0      1.0        31.0        40.0   
3  0.00       2.65        4.29  ...     0.0      4.0        29.0        34.0   
4  0.14       6.81        8.59  ...     1.0      2.0        31.0        38.0   

   aqi_o3_8hr  aqi_pm10  aqi_pm2_5  aqi_site       date      time  
0        36.0      29.0       25.0      30.0  04-Oct-23  18:00:00  
1        39.0      30.0       25.0      37.0  04-Oct-23  18:00:00  
2        45.0      32.0       25.0      45.0  04-Oct-23  18:00:00  
3        38.0      32.0       25.0      34.0  04-Oct-23  17:00:00  
4        46.0      33.0       25.0      46.0  04-Oct-23  17:00:00  

[5 rows x 22 columns]

In [60]:
df['time'] = pd.to_datetime(df['time'])
df['time'] = df['time'].dt.hour.astype(float)

df.head()


name                       gps  datetime    no2  o3_1hr  o3_4hr  o3_8hr  \
0   Civic  (-35.285307, 149.131579)      10.0    NaN   0.024   0.024   0.023   
1  Monash  (-35.418302, 149.094018)      10.0  0.003   0.031   0.030   0.025   
2  Florey  (-35.220606, 149.043539)      10.0  0.001   0.031   0.032   0.029   
3  Monash  (-35.418302, 149.094018)      10.0  0.005   0.029   0.027   0.025   
4  Florey  (-35.220606, 149.043539)      10.0  0.003   0.031   0.030   0.029   

     co  pm10_1_hr  pm2_5_1_hr  ...  aqi_co  aqi_no2  aqi_o3_1hr  aqi_o3_4hr  \
0  0.00       8.14        7.93  ...     0.0      0.0        24.0        30.0   
1  0.00       1.54        2.36  ...     0.0      3.0        31.0        37.0   
2  0.14       5.57        8.02  ...     1.0      1.0        31.0        40.0   
3  0.00       2.65        4.29  ...     0.0      4.0        29.0        34.0   
4  0.14       6.81        8.59  ...     1.0      2.0        31.0        38.0   

   aqi_o3_8hr  aqi_pm10  aqi_pm2_5  aqi_site       date  time  
0        36.0      29.0       25.0      30.0  04-Oct-23  18.0  
1        39.0      30.0       25.0      37.0  04-Oct-23  18.0  
2        45.0      32.0       25.0      45.0  04-Oct-23  18.0  
3        38.0      32.0       25.0      34.0  04-Oct-23  17.0  
4        46.0      33.0       25.0      46.0  04-Oct-23  17.0  

[5 rows x 22 columns]

In [61]:
location_mapping = {'Civic': 1, 'Monash': 2, 'Florey': 3}

df['name'] = df['name'].map(location_mapping).astype(float)
df.head()

name                       gps  datetime    no2  o3_1hr  o3_4hr  o3_8hr  \
0   1.0  (-35.285307, 149.131579)      10.0    NaN   0.024   0.024   0.023   
1   2.0  (-35.418302, 149.094018)      10.0  0.003   0.031   0.030   0.025   
2   3.0  (-35.220606, 149.043539)      10.0  0.001   0.031   0.032   0.029   
3   2.0  (-35.418302, 149.094018)      10.0  0.005   0.029   0.027   0.025   
4   3.0  (-35.220606, 149.043539)      10.0  0.003   0.031   0.030   0.029   

     co  pm10_1_hr  pm2_5_1_hr  ...  aqi_co  aqi_no2  aqi_o3_1hr  aqi_o3_4hr  \
0  0.00       8.14        7.93  ...     0.0      0.0        24.0        30.0   
1  0.00       1.54        2.36  ...     0.0      3.0        31.0        37.0   
2  0.14       5.57        8.02  ...     1.0      1.0        31.0        40.0   
3  0.00       2.65        4.29  ...     0.0      4.0        29.0        34.0   
4  0.14       6.81        8.59  ...     1.0      2.0        31.0        38.0   

   aqi_o3_8hr  aqi_pm10  aqi_pm2_5  aqi_site       date  time  
0        36.0      29.0       25.0      30.0  04-Oct-23  18.0  
1        39.0      30.0       25.0      37.0  04-Oct-23  18.0  
2        45.0      32.0       25.0      45.0  04-Oct-23  18.0  
3        38.0      32.0       25.0      34.0  04-Oct-23  17.0  
4        46.0      33.0       25.0      46.0  04-Oct-23  17.0  

[5 rows x 22 columns]

In [62]:
print(df.columns)

Index(['name', 'gps', 'datetime', 'no2', 'o3_1hr', 'o3_4hr', 'o3_8hr', 'co',
       'pm10_1_hr', 'pm2_5_1_hr', 'pm10', 'pm2_5', 'aqi_co', 'aqi_no2',
       'aqi_o3_1hr', 'aqi_o3_4hr', 'aqi_o3_8hr', 'aqi_pm10', 'aqi_pm2_5',
       'aqi_site', 'date', 'time'],
      dtype='object')


In [63]:
df.drop(['gps', 'date', 'aqi_co', 'aqi_no2',
        'aqi_o3_1hr', 'aqi_o3_4hr', 'aqi_o3_8hr', 'aqi_pm10', 'aqi_pm2_5'],axis='columns',inplace=True)

df.head()


name  datetime    no2  o3_1hr  o3_4hr  o3_8hr    co  pm10_1_hr  pm2_5_1_hr  \
0   1.0      10.0    NaN   0.024   0.024   0.023  0.00       8.14        7.93   
1   2.0      10.0  0.003   0.031   0.030   0.025  0.00       1.54        2.36   
2   3.0      10.0  0.001   0.031   0.032   0.029  0.14       5.57        8.02   
3   2.0      10.0  0.005   0.029   0.027   0.025  0.00       2.65        4.29   
4   3.0      10.0  0.003   0.031   0.030   0.029  0.14       6.81        8.59   

    pm10  pm2_5  aqi_site  time  
0  14.71   6.45      30.0  18.0  
1  15.25   6.43      37.0  18.0  
2  16.03   6.27      45.0  18.0  
3  16.20   6.40      34.0  17.0  
4  16.72   6.26      46.0  17.0

In [64]:
def classify(v):
    if 0 <= v <=33: #Very Good
        return 1
    elif 34 <= v <=66: #Good
        return 2
    elif 67 <= v <=99: #Fair
        return 3
    elif 100 <= v <=149: #Poor
        return 4
    elif 150 <= v <=200: #Very Poor
        return 5
    elif 150 <= v <=200: #Hazardous
        return 6
    
df['aqi_site'] = df['aqi_site'].apply(classify)

df.head()

name  datetime    no2  o3_1hr  o3_4hr  o3_8hr    co  pm10_1_hr  pm2_5_1_hr  \
0   1.0      10.0    NaN   0.024   0.024   0.023  0.00       8.14        7.93   
1   2.0      10.0  0.003   0.031   0.030   0.025  0.00       1.54        2.36   
2   3.0      10.0  0.001   0.031   0.032   0.029  0.14       5.57        8.02   
3   2.0      10.0  0.005   0.029   0.027   0.025  0.00       2.65        4.29   
4   3.0      10.0  0.003   0.031   0.030   0.029  0.14       6.81        8.59   

    pm10  pm2_5  aqi_site  time  
0  14.71   6.45       1.0  18.0  
1  15.25   6.43       2.0  18.0  
2  16.03   6.27       2.0  18.0  
3  16.20   6.40       2.0  17.0  
4  16.72   6.26       2.0  17.0

In [65]:
y = df.aqi_site
X = df.drop('aqi_site', axis='columns')

In [66]:
# make into method

X.o3_1hr = pd.to_numeric(X.o3_1hr, errors='coerce').astype(float)
X.o3_4hr = pd.to_numeric(X.o3_4hr, errors='coerce').astype(float)
X.o3_8hr = pd.to_numeric(X.o3_8hr, errors='coerce').astype(float)
X.co = pd.to_numeric(X.co, errors='coerce').astype(float)
X.pm10_1_hr = pd.to_numeric(X.pm10_1_hr, errors='coerce').astype(float)
X.pm2_5_1_hr = pd.to_numeric(X.pm2_5_1_hr, errors='coerce').astype(float)
X.pm10 = pd.to_numeric(X.pm10, errors='coerce').astype(float)
X.pm2_5 = pd.to_numeric(X.pm2_5, errors='coerce').astype(float)
X.no2 = pd.to_numeric(X.no2, errors='coerce').astype(float)

X.o3_1hr = X.o3_1hr.fillna(X.o3_1hr.mean())
X.o3_4hr = X.o3_4hr.fillna(X.o3_4hr.mean())
X.o3_8hr = X.o3_8hr.fillna(X.o3_4hr.mean())
X.co = X.co.fillna(X.co.mean())
X.pm10_1_hr = X.pm10_1_hr.fillna(X.pm10_1_hr.mean())
X.pm2_5_1_hr = X.pm2_5_1_hr.fillna(X.pm2_5_1_hr.mean())
X.pm10 = X.pm10.fillna(X.pm10.mean())
X.pm2_5 = X.pm2_5.fillna(X.pm2_5.mean())
X.no2 = X.no2.fillna(X.no2.mean())

X.head()

name  datetime       no2  o3_1hr  o3_4hr  o3_8hr    co  pm10_1_hr  \
0   1.0      10.0  0.004166   0.024   0.024   0.023  0.00       8.14   
1   2.0      10.0  0.003000   0.031   0.030   0.025  0.00       1.54   
2   3.0      10.0  0.001000   0.031   0.032   0.029  0.14       5.57   
3   2.0      10.0  0.005000   0.029   0.027   0.025  0.00       2.65   
4   3.0      10.0  0.003000   0.031   0.030   0.029  0.14       6.81   

   pm2_5_1_hr   pm10  pm2_5  time  
0        7.93  14.71   6.45  18.0  
1        2.36  15.25   6.43  18.0  
2        8.02  16.03   6.27  18.0  
3        4.29  16.20   6.40  17.0  
4        8.59  16.72   6.26  17.0

In [67]:
has_nan = y.isna
print(has_nan)

<bound method Series.isna of 0        1.0
1        2.0
2        2.0
3        2.0
4        2.0
        ... 
19942    1.0
19943    1.0
19944    1.0
19945    1.0
19946    1.0
Name: aqi_site, Length: 19947, dtype: float64>


In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=17)

In [77]:
df_train = pd.DataFrame(data=np.column_stack((X_train, y_train)), columns=['name', 'datetime', 'no2', 'o3_1hr', 'o3_4hr', 'o3_8hr', 'co',
       'pm10_1_hr', 'pm2_5_1_hr', 'pm10', 'pm2_5', 'time', 'aqi_site'])

In [78]:
model = sm.GLM.from_formula('aqi_site ~ name + datetime + no2 + o3_1hr + o3_4hr + o3_8hr + co + pm10_1_hr + pm2_5_1_hr + pm10 + pm2_5 + time', family=sm.families.Gaussian(), data=df_train)
result = model.fit()

In [75]:
df_test = pd.DataFrame(data=np.column_stack((X_test, y_test)), columns=['name', 'datetime', 'no2', 'o3_1hr', 'o3_4hr', 'o3_8hr', 'co',
        'pm10_1_hr', 'pm2_5_1_hr', 'pm10', 'pm2_5', 'time', 'aqi_site'])
y_pred = np.round(result.predict(df_test))

In [76]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.0005012531328320802


In [ ]:
print('Accuracy = ',accuracy_score(y_expect, y_pred))
print('Precision = ',precision_score(y_expect, y_pred, average='macro'))
print('Recall = ',recall_score(y_expect, y_pred, average='macro'))
print('F1 = ',f1_score(y_expect, y_pred, average='macro'))

print('Confusion Matrix')
print(confusion_matrix(y_expect, y_pred))

Accuracy =  0.7969924812030075
Precision =  0.6594285105329676
Recall =  0.8315852776819123
F1 =  0.7147128982213282
Confusion Matrix =  [[2126  241    2    0]
 [ 375  946  165    0]
 [   0   24  103    3]
 [   0    0    0    5]]
